PORTNAME=	esp-llvm-embedded-toolchain-libs-clang
COMMENT=	Clang libs with support the RISC-V and Xtensa architecture (libs-clang)

MASTERDIR=	${.CURDIR}/../esp-llvm-embedded-toolchain
ESP_TARGET=	llvm-standalone-libs

.include "${MASTERDIR}/Makefile"
