PORTNAME=	wokwi-server
DISTVERSION=	0.2.0
DISTVERSIONPREFIX=	v
CATEGORIES=	emulators
MASTER_SITES=

MAINTAINER=	y@trombik.org
COMMENT=	CLI tool for launching a wokwi instance

LICENSE=	MIT APACHE20
LICENSE_COMB=	dual

WWW=	https://github.com/MabezDev/wokwi-server
USES=	cargo
USE_GITHUB=	yes
GH_TUPLE=	MabezDev:${PORTNAME}:${DISTVERSIONPREFIX}${PORTVERSION}

.include <bsd.port.mk>
