PORTNAME=	riscv32-esp-elf
COMMENT=	Espressif ESP32 toolchain for RISC-V-based MCUs
FLAVORS=	idf60 idf55 idf54 idf53
FLAVOR?=	${FLAVORS:[1]}
MASTERDIR=	${.CURDIR}/../xtensa-esp-elf

.include "${MASTERDIR}/Makefile"
