---
name: Look for changed ports
on:
  - push

jobs:
  list-ports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            ports-to-build: "*/**"
            ci: ".github/workflows/*.yml"

      - name: Build all ports in the repository
        if: steps.filter.outputs.ci == 'true'
        run: |
          echo "::notice ::'${{ steps.filter.outputs.ci_files }}'"

      - name: Build ports-to-build
        if: steps.filter.outputs.ports-to-build == 'true' && steps.filter.outputs.ci != 'true'
        run: |
          echo "::notice ::'${{ steps.filter.outputs.ports-to-build_files }}'"
