---
name: Look for changed ports
on:
  - push

jobs:
  list-ports:
    runs-on: ubuntu-latest
    outputs:
      PORTS_TO_BUILD_JSON: ${{ steps.list-ports-to-build.outputs.PORTS_TO_BUILD_JSON }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            ports-to-build:
              - "[0-9a-zA-Z]*/**"
            ci:
              - ".github/workflows/*.yml"

      - name: Build all ports in the repository
        if: steps.filter.outputs.ci == 'true'
        run: |
          echo "steps.filter.outputs.ci_files: '${{ steps.filter.outputs.ci_files }}'"
          echo "::notice ::Building all the ports in the repository"

      - name: List ports-to-build
        if: steps.filter.outputs.ports-to-build == 'true' && steps.filter.outputs.ci != 'true'
        id: list-ports-to-build
        run: |
          echo "steps.filter.outputs.ports-to-build_files: 'steps.filter.outputs.ports-to-build_files }}'"
          # find ports in the repository and make it a list of one line
          # separated by a space.
          PORTS_TO_BUILD=`find * -type d -maxdepth 1 -mindepth 1 | tr '\n' ' ' | sed -e 's/ $//'`
          echo "::notice ::Building ${PORTS_TO_BUILD}"

          # create a JSON from the list
          PORTS_TO_BUILD_JSON=`jq -n -c -M --arg V "${PORTS_TO_BUILD}" '{ PORT: ($V | split(" ")) }'`

          # pass the JSON to other jobs
          echo "PORTS_TO_BUILD_JSON=${PORTS_TO_BUILD_JSON}" >> "${GITHUB_OUTPUT}"
          cat "${GITHUB_OUTPUT}"

  build-ports:
    runs-on: ubuntu-latest
    needs: list-ports
    steps:
      - name: Build ports
        run: |
          echo "${{ needs.list-ports.outputs.PORTS_TO_BUILD_JSON }}"
