---
name: Look for changed ports
on:
  - push

jobs:
  list-ports:
    runs-on: ubuntu-latest
    outputs:
      PORTS_TO_BUILD: ${{ steps.list-ports-to-build.outputs.PORTS_TO_BUILD }}
      BUILD_ALL_PORTS_JSON: ${{ steps.build-all-ports.outputs.BUILD_ALL_PORTS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Filter changed paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            ports-to-build:
              - "[0-9a-zA-Z]*/**"
            ci:
              - ".github/workflows/*.yml"

      - name: Build all ports in the repository
        if: steps.filter.outputs.ci == 'true'
        id: build-all-ports
        run: |
          echo "steps.filter.outputs.ci_files: '${{ steps.filter.outputs.ci_files }}'"
          echo "::notice ::Building all the ports in the repository"

          # find ports in the repository and make it a list of one line
          # separated by a space.
          PORTS_TO_BUILD=`find * -type d -maxdepth 1 -mindepth 1 | tr '\n' ' ' | sed -e 's/ $//'`

          # pass the JSON to other jobs
          echo "BUILD_ALL_PORTS=${PORTS_TO_BUILD}" >> "${GITHUB_OUTPUT}"
          cat "${GITHUB_OUTPUT}"

      - name: List ports-to-build
        if: steps.filter.outputs.ports-to-build == 'true' && steps.filter.outputs.ci != 'true'
        id: list-ports-to-build
        run: |
          echo "steps.filter.outputs.ports-to-build_files: '${{ steps.filter.outputs.ports-to-build_files }}'"

          # find changed ports in the repository and make it a list of one
          # line separated by a space.
          for F in ${{ steps.filter.outputs.ports-to-build_files }}; do
            PORTS_TO_BUILD="${PORTS_TO_BUILD} `echo ${F} | cut -f 1,2 -d '/' | sort -u | grep '/'`
          done
          PORTS_TO_BUILD=`echo ${PORTS_TO_BUILD} | tr '\n' ' ' | sed -e 's/ $//'`
          echo "::notice ::Building ${PORTS_TO_BUILD}"

          # pass the JSON to other jobs
          echo "PORTS_TO_BUILD=${PORTS_TO_BUILD}" >> "${GITHUB_OUTPUT}"
          cat "${GITHUB_OUTPUT}"

  build-ports:
    runs-on: ubuntu-latest
    needs: list-ports
    steps:
      - name: Build ports
        shell: sh
        run: |
          if [ ! -z needs.list-ports.outputs.BUILD_ALL_PORTS_JSON ]; then
            echo "Building ${{ needs.list-ports.outputs.BUILD_ALL_PORTS_JSON }}"
          elif [ -z ${{ needs.list-ports.outputs.PORTS_TO_BUILD_JSON }}; then
            echo "Building ${{ needs.list-ports.outputs.PORTS_TO_BUILD_JSON }}"
          else
            echo "Building none"
          fi
